logging:
  level:
    root: info
amazon:
  dynamodb:
    endpoint: http://localhost:8000
    region: ap-northeast-1
  aws:
    accesskey: local
    secretkey: local
spring:
  devtools:
    restart:
      enabled: true
# spring security + aws cognito
  security:
    oauth2:
      client:
        registration:
          cognito:
            provider: cognito
            client-id: 3sfi093tp5ik6o6al9lj9134g6
            client-secret: lllpmd9rmn3h1vn7t7h19vvife2qgv2kp1nlafvq2ujg6on9usl
            client-name: demo-client
            authorization-grant-type: authorization_code
            scope: email,openid
            redirect-uri-template: ${app.url}/login/oauth2/code/cognito
        provider:
          cognito:
            authorizationUri: ${cognito.rooturl}/oauth2/authorize
            tokenUri: ${cognito.rooturl}/oauth2/token
            jwkSetUri: https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_C6Vw8lvBy/.well-known/jwks.json
            user-info-uri: ${cognito.rooturl}/oauth2/userInfo
            userNameAttribute: username
app:
  url: http://localhost:8080
cognito:
  rooturl: https://demo-userpool.auth.ap-northeast-1.amazoncognito.com

