logging:
  level:
    root: info
    com:
      haruspring:
        sample:
          dynamodb:
            sdk: debug
amazon:
  dynamodb:
    endpoint: http://localhost:8000
    region: ap-northeast-1
  aws:
    accesskey: local
    secretkey: local
spring:
  devtools:
    restart:
      enabled: true